[package]
name = "assign-transfer-test"
edition.workspace = true
version.workspace = true

[features]
default = []
test-sbf = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
jiminy-cpi = { workspace = true }
jiminy-entrypoint = { workspace = true }
jiminy-sysvar-rent = { workspace = true }
sanctum-system-jiminy = { workspace = true }

[dev-dependencies]
mollusk-svm = { workspace = true }
proptest = { workspace = true }
solana-account = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }
sanctum-system-test-utils = { workspace = true }
