[workspace]
resolver = "2"

members = [
    "core",
    "jiminy",
    "tests/solana-comp", 
]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
# In general, keep default-features = false in workspace
# and enable individual features in indiv crates
generic-array-struct = { version = "=0.3.0-bc", default-features = false }

# jiminy crates
jiminy-cpi = { git = "https://github.com/igneous-labs/jiminy.git", branch = "master" }

# dev deps
proptest = { version = "^1" }

# solana crates (for dev)
solana-instruction = "^2"
solana-pubkey = "^2"
solana-system-interface = "^1"

# workspace members
sanctum-system-core = { path = "core" }
