[workspace]
resolver = "2"

members = [
    "core",
    "jiminy",
    "tests/solana-comp",
    "tests/test-programs/*",
    "tests/test-utils",
]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
# In general, keep default-features = false in workspace
# and enable individual features in indiv crates.
# Dont really care as much for dev deps
generic-array-struct = { version = "^0.3.2", default-features = false }

# jiminy crates
jiminy-cpi = { git = "https://github.com/igneous-labs/jiminy.git", branch = "master" }
jiminy-entrypoint = { git = "https://github.com/igneous-labs/jiminy.git", branch = "master" }
jiminy-sysvar-rent = { git = "https://github.com/igneous-labs/jiminy.git", branch = "master" }

# dev deps
expect-test = "^1"
proptest = "^1"

# solana crates (for dev)
mollusk-svm = "^0.9"
solana-account = "^3"
solana-instruction = "^3"
solana-logger = "^3"
solana-pubkey = "^3"
solana-system-interface = "^3"

# workspace members
sanctum-system-core = { path = "core" }
sanctum-system-jiminy = { path = "jiminy" }
sanctum-system-test-utils = { path = "./tests/test-utils" }
